import { Chip8Config, COSMAC_VIP_CONFIG, HP48_CONFIG } from "./interpreter";

export const PROGRAMS = new Map<string, string>([
  ["15 Puzzle", "15 Puzzle [Roger Ivie].ch8"],
  ["Addition Problems", "Addition Problems [Paul C. Moews].ch8"],
  ["Airplane", "Airplane.ch8"],
  ["Animal Race", "Animal Race [Brian Astle].ch8"],
  ["Astro Dodge", "Astro Dodge [Revival Studios, 2008].ch8"],
  ["BMP Viewer - Hello", "BMP Viewer - Hello (C8 example) [Hap, 2005].ch8"],
  ["Biorhythm", "Biorhythm [Jef Winsor].ch8"],
  ["Blinky", "Blinky [Hans Christian Egeberg, 1991].ch8"],
  ["Blitz", "Blitz [David Winter].ch8"],
  ["Bowling", "Bowling [Gooitzen van der Wal].ch8"],
  ["Breakout (Brix hack)", "Breakout (Brix hack) [David Winter, 1997].ch8"],
  ["Breakout", "Breakout [Carmelo Cortez, 1979].ch8"],
  ["Brick", "Brick (Brix hack, 1990).ch8"],
  ["Brix", "Brix [Andreas Gustafsson, 1990].ch8"],
  ["Cave", "Cave.ch8"],
  ["Chip8 Picture", "Chip8 Picture.ch8"],
  ["Chip8 Emulator Logo", "Chip8 emulator Logo [Garstyciuks].ch8"],
  ["Chipquarium", "modern/chipquarium.ch8"],
  ["Clock Program", "Clock Program [Bill Fisher, 1981].ch8"],
  ["Coin Flipping", "Coin Flipping [Carmelo Cortez, 1978].ch8"],
  ["Connect 4", "Connect 4 [David Winter].ch8"],
  ["Craps", "Craps [Camerlo Cortez, 1978].ch8"],
  ["Deflection", "Deflection [John Fort].ch8"],
  ["Delay Timer Test", "Delay Timer Test [Matthew Mikolay, 2010].ch8"],
  ["Division Test", "Division Test [Sergey Naydenov, 2010].ch8"],
  ["Figures", "Figures.ch8"],
  ["Filter", "Filter.ch8"],
  ["Fishie", "Fishie [Hap, 2005].ch8"],
  ["Framed MK1", "Framed MK1 [GV Samways, 1980].ch8"],
  ["Framed MK2", "Framed MK2 [GV Samways, 1980].ch8"],
  ["Glitch Ghost", "modern/glitchGhost.ch8"],
  ["Guess", "Guess [David Winter].ch8"],
  ["Hi-Lo", "Hi-Lo [Jef Winsor, 1978].ch8"],
  ["Hidden", "Hidden [David Winter, 1996].ch8"],
  ["IBM Logo", "IBM Logo.ch8"],
  ["Jumping X and O", "Jumping X and O [Harry Kleinberg, 1977].ch8"],
  ["Kaleidoscope", "Kaleidoscope [Joseph Weisbecker, 1978].ch8"],
  ["Keypad Test", "Keypad Test [Hap, 2006].ch8"],
  ["Landing", "Landing.ch8"],
  ["Life", "Life [GV Samways, 1980].ch8"],
  ["Lunar Lander", "Lunar Lander (Udo Pernisz, 1979).ch8"],
  ["Mastermind FourRow", "Mastermind FourRow (Robert Lindley, 1978).ch8"],
  ["Maze", "Maze [David Winter, 199x].ch8"],
  ["Merlin", "Merlin [David Winter].ch8"],
  ["Minimal game", "Minimal game [Revival Studios, 2007].ch8"],
  ["Missile", "Missile [David Winter].ch8"],
  ["Most Dangerous Game", "Most Dangerous Game [Peter Maruhnic].ch8"],
  ["Nim", "Nim [Carmelo Cortez, 1978].ch8"],
  ["Octojam 7 Title", "modern/octojam7title.ch8"],
  ["Paddles", "Paddles.ch8"],
  ["Particle Demo", "Particle Demo [zeroZshadow, 2008].ch8"],
  ["Pet Dog", "modern/petdog.ch8"],
  ["Pong (1 player)", "Pong (1 player).ch8"],
  ["Pong (alt)", "Pong (alt).ch8"],
  ["Pong 2 (Pong hack)", "Pong 2 (Pong hack) [David Winter, 1997].ch8"],
  ["Pong", "Pong [Paul Vervalin, 1990].ch8"],
  ["Prog. Spacefighters", "Programmable Spacefighters [Jef Winsor].ch8"],
  ["Puzzle", "Puzzle.ch8"],
  ["Random Number Test", "Random Number Test [Matthew Mikolay, 2010].ch8"],
  ["Reversi", "Reversi [Philip Baltzer].ch8"],
  ["Rocket Launch", "Rocket Launch [Jonas Lindstedt].ch8"],
  ["Rocket Launcher", "Rocket Launcher.ch8"],
  ["Rocket", "Rocket [Joseph Weisbecker, 1978].ch8"],
  ["Rush Hour", "Rush Hour [Hap, 2006].ch8"],
  ["Russian Roulette", "Russian Roulette [Carmelo Cortez, 1978].ch8"],
  ["SQRT Test", "SQRT Test [Sergey Naydenov, 2010].ch8"],
  ["Sequence Shoot", "Sequence Shoot [Joyce Weisbecker].ch8"],
  ["Shooting Stars", "Shooting Stars [Philip Baltzer, 1978].ch8"],
  ["Sierpinski", "Sierpinski [Sergey Naydenov, 2010].ch8"],
  ["Slide", "Slide [Joyce Weisbecker].ch8"],
  ["Soccer", "Soccer.ch8"],
  ["Space Flight", "Space Flight.ch8"],
  ["Space Intercept", "Space Intercept [Joseph Weisbecker, 1978].ch8"],
  ["Space Invaders", "Space Invaders [David Winter].ch8"],
  ["Spooky Spot", "Spooky Spot [Joseph Weisbecker, 1978].ch8"],
  ["Squash", "Squash [David Winter].ch8"],
  ["Stars", "Stars [Sergey Naydenov, 2010].ch8"],
  ["Submarine", "Submarine [Carmelo Cortez, 1978].ch8"],
  ["Sum Fun", "Sum Fun [Joyce Weisbecker].ch8"],
  ["Syzygy", "Syzygy [Roy Trevino, 1990].ch8"],
  ["Tank", "Tank.ch8"],
  ["Tapeworm", "Tapeworm [JDR, 1999].ch8"],
  ["Tetris", "Tetris [Fran Dachille, 1991].ch8"],
  ["Tic-Tac-Toe", "Tic-Tac-Toe [David Winter].ch8"],
  ["Timebomb", "Timebomb.ch8"],
  ["Trip8 Demo", "Trip8 Demo (2008) [Revival Studios].ch8"],
  ["Tron", "Tron.ch8"],
  ["UFO", "UFO [Lutz V, 1992].ch8"],
  ["Vers", "Vers [JMN, 1991].ch8"],
  ["Vertical Brix", "Vertical Brix [Paul Robson, 1996].ch8"],
  ["Wall", "Wall [David Winter].ch8"],
  ["Wipe Off", "Wipe Off [Joseph Weisbecker].ch8"],
  ["Worm V4", "Worm V4 [RB-Revival Studios, 2007].ch8"],
  ["X-Mirror", "X-Mirror.ch8"],
  ["Zero Demo", "Zero Demo [zeroZshadow, 2007].ch8"],
  ["ZeroPong", "ZeroPong [zeroZshadow, 2007].ch8"],
  ["Test 1: Chip-8 Logo", "tests/1-chip8-logo.ch8"],
  ["Test 2: IBM Logo", "tests/2-ibm-logo.ch8"],
  ["Test 3: Corax+ (COSMAC)", "tests/3-corax+.ch8"],
  ["Test 3: Corax+ (HP48)", "tests/3-corax+.ch8"],
  ["Test 4: Flags", "tests/4-flags.ch8"],
  ["Test 5: Quirks (COSMAC)", "tests/5-quirks.ch8"],
  ["Test 5: Quirks (HP48)", "tests/5-quirks.ch8"],
  ["Test 6: Keypad", "tests/6-keypad.ch8"],
  ["Test 7: Beep", "tests/7-beep.ch8"],
]);

export const PROGRAM_CONFIGS = new Map<string, Chip8Config>([
  ["15 Puzzle", HP48_CONFIG],
  ["Addition Problems", HP48_CONFIG],
  ["Airplane", HP48_CONFIG],
  ["Animal Race", COSMAC_VIP_CONFIG],
  ["Astro Dodge", HP48_CONFIG],
  ["BMP Viewer - Hello", HP48_CONFIG],
  ["Biorhythm", COSMAC_VIP_CONFIG],
  ["Blinky", HP48_CONFIG],
  ["Blitz", HP48_CONFIG],
  ["Bowling", COSMAC_VIP_CONFIG],
  ["Breakout (Brix hack)", HP48_CONFIG],
  ["Breakout", COSMAC_VIP_CONFIG],
  ["Brick", HP48_CONFIG],
  ["Brix", HP48_CONFIG],
  ["Cave", HP48_CONFIG],
  ["Chip8 Picture", HP48_CONFIG],
  ["Chip8 Emulator Logo", HP48_CONFIG],
  ["Clock Program", COSMAC_VIP_CONFIG],
  ["Chipquarium", HP48_CONFIG],
  ["Coin Flipping", COSMAC_VIP_CONFIG],
  ["Connect 4", HP48_CONFIG],
  ["Craps", COSMAC_VIP_CONFIG],
  ["Deflection", COSMAC_VIP_CONFIG],
  ["Delay Timer Test", HP48_CONFIG],
  ["Division Test", HP48_CONFIG],
  ["Figures", HP48_CONFIG],
  ["Filter", HP48_CONFIG],
  ["Fishie", HP48_CONFIG],
  ["Framed MK1", COSMAC_VIP_CONFIG],
  ["Framed MK2", COSMAC_VIP_CONFIG],
  ["Glitch Ghost", COSMAC_VIP_CONFIG],
  ["Guess", HP48_CONFIG],
  ["Hi-Lo", COSMAC_VIP_CONFIG],
  ["Hidden", HP48_CONFIG],
  ["IBM Logo", HP48_CONFIG],
  ["Jumping X and O", COSMAC_VIP_CONFIG],
  ["Kaleidoscope", COSMAC_VIP_CONFIG],
  ["Keypad Test", HP48_CONFIG],
  ["Landing", HP48_CONFIG],
  ["Life", COSMAC_VIP_CONFIG],
  ["Lunar Lander", COSMAC_VIP_CONFIG],
  ["Mastermind FourRow", COSMAC_VIP_CONFIG],
  ["Maze", HP48_CONFIG],
  ["Merlin", HP48_CONFIG],
  ["Minimal game", HP48_CONFIG],
  ["Missile", HP48_CONFIG],
  ["Most Dangerous Game", COSMAC_VIP_CONFIG],
  ["Nim", COSMAC_VIP_CONFIG],
  ["Octojam 7 Title", HP48_CONFIG],
  ["Paddles", HP48_CONFIG],
  ["Particle Demo", HP48_CONFIG],
  ["Pet Dog", HP48_CONFIG],
  ["Pong (1 player)", HP48_CONFIG],
  ["Pong (alt)", HP48_CONFIG],
  ["Pong 2 (Pong hack)", HP48_CONFIG],
  ["Pong", HP48_CONFIG],
  ["Prog. Spacefighters", COSMAC_VIP_CONFIG],
  ["Puzzle", HP48_CONFIG],
  ["Random Number Test", HP48_CONFIG],
  ["Reversi", COSMAC_VIP_CONFIG],
  ["Rocket Launch", HP48_CONFIG],
  ["Rocket Launcher", HP48_CONFIG],
  ["Rocket", COSMAC_VIP_CONFIG],
  ["Rush Hour", HP48_CONFIG],
  ["Russian Roulette", COSMAC_VIP_CONFIG],
  ["SQRT Test", HP48_CONFIG],
  ["Sequence Shoot", COSMAC_VIP_CONFIG],
  ["Shooting Stars", COSMAC_VIP_CONFIG],
  ["Sierpinski", HP48_CONFIG],
  ["Slide", COSMAC_VIP_CONFIG],
  ["Soccer", HP48_CONFIG],
  ["Space Flight", HP48_CONFIG],
  ["Space Intercept", COSMAC_VIP_CONFIG],
  ["Space Invaders", HP48_CONFIG],
  ["Spooky Spot", COSMAC_VIP_CONFIG],
  ["Squash", HP48_CONFIG],
  ["Stars", HP48_CONFIG],
  ["Submarine", COSMAC_VIP_CONFIG],
  ["Sum Fun", COSMAC_VIP_CONFIG],
  ["Syzygy", HP48_CONFIG],
  ["Tank", HP48_CONFIG],
  ["Tapeworm", HP48_CONFIG],
  ["Tetris", HP48_CONFIG],
  ["Tic-Tac-Toe", HP48_CONFIG],
  ["Timebomb", HP48_CONFIG],
  ["Trip8 Demo", HP48_CONFIG],
  ["Tron", HP48_CONFIG],
  ["UFO", HP48_CONFIG],
  ["Vers", HP48_CONFIG],
  ["Vertical Brix", HP48_CONFIG],
  ["Wall", HP48_CONFIG],
  ["Wipe Off", COSMAC_VIP_CONFIG],
  ["Worm V4", HP48_CONFIG],
  ["X-Mirror", HP48_CONFIG],
  ["Zero Demo", HP48_CONFIG],
  ["ZeroPong", HP48_CONFIG],
  ["Test 1: Chip-8 Logo", COSMAC_VIP_CONFIG],
  ["Test 2: IBM Logo", COSMAC_VIP_CONFIG],
  ["Test 3: Corax+ (COSMAC)", COSMAC_VIP_CONFIG],
  ["Test 3: Corax+ (HP48)", HP48_CONFIG],
  ["Test 4: Flags", COSMAC_VIP_CONFIG],
  ["Test 5: Quirks (COSMAC)", COSMAC_VIP_CONFIG],
  ["Test 5: Quirks (HP48)", HP48_CONFIG],
  ["Test 6: Keypad", COSMAC_VIP_CONFIG],
  ["Test 7: Beep", COSMAC_VIP_CONFIG],
]);

export const EXCLUDE_PROGRAMS = [
  "Breakout", // buggy
  "Delay Timer Test",
  "Division Test",
  "Figures",
  "Random Number Test",
  "Slide", // keyboard issues?
  "Sum Fun", // keyboard issues?
  "Test 1: Chip-8 Logo",
  "Test 2: IBM Logo",
  "Test 3: Corax+ (COSMAC)",
  "Test 3: Corax+ (HP48)",
  "Test 4: Flags",
  "Test 5: Quirks (COSMAC)",
  "Test 5: Quirks (HP48)",
  "Test 6: Keypad",
  "Test 7: Beep",
];
